dist: xenial
os: linux
language: shell

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

jobs:
  include:
    - stage: setup files
      script: ./deploy_ci.sh

branches:
  only:
    - main
