version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Install AWS CLI
          command: |
            pip install -U pip
            pip install awscli
      - run:
          name: Deploy
          command: ./deploy_ci.sh

workflows:
  deploy:
    jobs:
      - deploy
