version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run: ./deploy_ci.sh

workflows:
  deploy:
    jobs:
      - deploy
